[package]
name = "art_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.9"
tree-sitter-rust = "0.20.3"
rust-code-analysis = "0.0.24"
image = "^0.24"
itertools = "0.10.5"
